language: php
php:
    - 5.4

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp behat.yml.dist behat.yml
    - composer install --dev --prefer-source > /dev/null
    - app/console do:da:cr -e=test > /dev/null
    - app/console do:sc:cr -e=test --no-interaction > /dev/null

    
script:
    - bin/phpspec run -fpretty --verbose
    - bin/behat --no-snippets --verbose -fpretty
